spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edu_online?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123abc
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: top.zshan.eduonline.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
  aop:
    auto: false
  #    filters: stat,wall
  #    tomcat:
  #      max-active: 12
  jdbc:
    template:
      query-timeout: 3
#  redis:
#    host: r-bp1rn3q03bst80w4vmpd.redis.rds.aliyuncs.com
#    #    url: redis://zshan:ZHUshan123@r-bp1rn3q03bst80w4vmpd.redis.rds.aliyuncs.com:6379
#    port: 6379
#    password: zshan:ZHUshan123
#    client-type: jedis
  boot:
    admin:
      client:
        url: http://localhost:8888
mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml 用了下面的配置 就不用写全局配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
